### ISSUE TITLE
Missing the Jupiter platform configuration

### ISSUE THREAD

**Issue by iuliana** [sbrannen/junit5-demo#2]
Your code snippet, is missing the  Jupiter platform configuration in the `build.gradle` file.  Because of this when running `gradle test` tests are not actually picked up. 

Add
`test {
	useJUnitPlatform()
}` 
for the project to be fully valid, even when build is run from the command line.

**Comment by sbrannen** [comment]
Hi @iuliana,

Which "snippet" are you referring to?

`build.gradle` properly configures the `test` task to use the JUnit Platform:

https://github.com/sbrannen/junit5-demo/blob/9aeb6987e07ac38a37a8de77d446bb9f58c1c45c/build.gradle#L52-L58

**Comment by iuliana** [comment]
I think I was building a different project. My bad. I'm sorry.

**Comment by sbrannen** [comment]
No worries. Thanks for the feedback.
