### ISSUE TITLE
How about making a library out of it?

### ISSUE THREAD

**Issue by mickaeltr** [sbrannen/junit5-demo#3]
Hello,

Thanks for your valuable extension. I copy-pasted the code in my project.
I was wondering why you didn't make a library out of it?

Cheers

**Comment by sbrannen** [comment]
Regarding the ones [here](https://github.com/sbrannen/junit5-demo/tree/master/src/main/java/org/junit/jupiter/api/condition), those were prototypes for inclusion in JUnit Jupiter, but we (the JUnit 5 team) decided not to include them.

If you're referring to the [@CaptureSystemOutput support](https://github.com/sbrannen/junit5-demo/blob/master/src/test/java/extensions/), that has recently been implemented in Spring Boot 2.2.

I am therefore closing this issue; however, if the above does not answer your question, feel free to provide further input here.

Thanks

**Comment by mickaeltr** [comment]
Thanks @sbrannen, I was talking about the CaptureSystemOutput. So I'll wait for Spring Boot 2.2 to be released, then I can use the [OutputCapture rule](https://github.com/spring-projects/spring-boot/issues/14738).
